### ISSUE TITLE
Generate a mini mappers.json

### ISSUE THREAD

**Issue by mark-cooper** [collectionspace/cspace-config-untangler#65]
For production we can set MAPPERS_URL to: https://raw.githubusercontent.com/collectionspace/cspace-config-untangler/main/data/mappers.json

But that's too much (slow) for dev environments so it would be good to have a mini-mappers.json with a smallish sample of mappers from across profiles and types -- perhaps ~ 8-15. With this we can delete the mappers.json file from cspace-batch-import and s3 and update MAPPERS_URL for dev to: https://raw.githubusercontent.com/collectionspace/cspace-config-untangler/main/data/mini-mappers.json (or other name as preferred).

**Comment by kspurgin** [comment]
Solved by #67
